knowledge_tags = [
    "Thư viện",
    "Cú pháp",
    "Nhập/xuất dữ liệu",
    "Kiểu dữ liệu",
    "Biến",
    "Toán tử",
    "Cấu trúc điều kiện",
    "Vòng lặp",
    "Mảng",
    "Hàm",
    "Con trỏ",
    "Chuỗi",
    "File",
    "Đệ quy",
    "Struct",
    "Con trỏ",
    "Hàng đợi",
    "Ngăn xếp",
    "Cây",
    "Đồ thị",
    "Sắp xếp",
    "Tìm kiếm",
    "Chia để trị",
    "Quy hoạch động",
    "Tham lam",
    "Đệ quy",
    "Bitmask",    
    "Không liên quan đến lập trình hay toán học"
]